database:
  sqlite:
    path: "data/discostar.db"
  
discogs:
  api:
    base_url: "https://api.discogs.com"
    rate_limit: 60  # requests per minute
    user_agent: "discostar/0.1.0"
    verify_ssl: false  # Set to false to disable SSL verification (for development)
  xml_dumps:
    base_url: "https://discogs-data-dumps.s3-us-west-2.amazonaws.com"
    artists_file: "discogs_artists.xml.gz"
    releases_file: "discogs_releases.xml.gz"
    labels_file: "discogs_labels.xml.gz"
    masters_file: "discogs_masters.xml.gz"

logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/discostar.log"

cache:
  directory: "data/cache"
  api_cache_ttl: 3600  # seconds

ingestion:
  batch_size: 1000  # Number of records to process in each batch
  commit_interval: 10000  # Commit after this many records
  max_error_rate: 0.1  # Maximum allowable error rate (10%)
  progress_update_interval: 1000  # Update progress every N records
  
  # Release ingestion strategy
  releases:
    strategy: "collection_only"  # Options: "all", "collection_only", "selective", "skip"
    # Note: "collection_only" requires collection data to be synced first
    
    # Master release expansion (for collection_only strategy)
    include_master_releases: true  # Include all releases linked to masters in collection
    
    # For selective strategy (future):
    include_artist_releases: false  # Include all releases from collection artists
    include_label_releases: false   # Include all releases from collection labels
    max_releases_per_artist: 50     # Limit releases per artist (for discovery)
    max_releases_per_label: 100     # Limit releases per label